### PR TITLE
Change 'lab' to 'library'

### PR DESCRIPTION
**Pull request by danmichaelo**
It's library carpentry after all :D

### CODE REVIEW

**Comment by danmichaelo** [comment]
Also changed pressures to temperatures, since measuring temperatures in a rare book could be a possible scenario. Pressure measurements in libraries are more rare.

**Comment by elliewix** [comment]
Hi Dan,
Thanks for the PR! Just wanting to give you some context behind a timeline for handling this. We (the maintainers) have seen this and will be discussing it during our next meeting (sometimes next week).

**Comment by danmichaelo** [comment]
Thanks for the feedback, @elliewix!

I noticed afterwards that the lesson was marked as in *alpha* stage and that there were also many other issues with it, both related to domain and to the flow of content (exercises based on topics that haven't yet been introduced etc.), so I ended up teaching the software carpentry version instead for our workshop today.

It would be great to have a working library carpentry python lesson though! Right now it seems like quite a major effort and I'm not quite sure where to start, but feel free to ping me if you have plans to bring this lesson out of alpha state, I'm quite interested in contributing to that.

**Comment by elliewix** [comment]
Hi Dan!

We were reviewing your changes here and really like your proposed rewriting of these examples.  We found that there are additional instances of the `pressure` example through other episodes.  This means we can't accept these changes until everything is consistent across the entire module.  

Would you be able to search through your branch of this for additional instances and propose edits to those other uses?  @lwrubel has added herself on here to try and identify the other places where they might be.

Please let us know if this is something that you could do within the next month? This will help us plan our development tasks, and we can add it to our list if you are unable to. We completely understand if you can't :-)

**Comment by lwrubel** [comment]
Thanks, @danmichaelo! We're merging this in to make this more relevant to library contexts. I noticed that this removes the discussion of extend(), so I'll create an issue to document that. We'll be doing a more involved overhaul in the coming months, which will likely touch this content again.

**Comment by danmichaelo** [comment]
Thanks for the merge!

And sorry for the removal of the extend exercise. While I don't think the exercise is library relevant, it certainly wasn't my intention to include it in this PR, that was a mistake on my side.

**Pull request merged**
